[package]
name = "rkv"
version = "0.1.0"
authors = ["Khaled K. Badr <khaledkbadr@outlook.com>"]

[dependencies]
byteorder = "1.2"
pretty_env_logger = "0.1"
openssl = "0.9"
bincode = "0.9"
serde_derive = "1.0"
serde = "1.0"
hex = "0.3"
atoi = "0.2"
